### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [Seraph27/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - please embed the link to "the official website" of VSC
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - please make sure you have the method you tried for this part of lab 1: Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then **copying it to the remote server and running it**.
  - (what you have right now is close to what we're looking for)
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by seraph27** [comment]
fixed!

**Comment by seraph27** [comment]
@farnaf Hello, I know this is closed 2 days ago, but on gradescope it still shows a 0. Does that mean my fix didn't meet the requirements or is this a mistake

**Comment by seraph27** [comment]
![image](https://user-images.githubusercontent.com/42664208/151152873-6e331b01-1bf9-446c-8336-f38408dd382f.png)

**Comment by farnaf** [comment]
Thanks for reaching out! No that was my mistake, sorry. Should be updated now

**Comment by seraph27** [comment]
Thank you. It is fixed now
